export const mockSongs = [
    {
        id: '1',
        title: 'Bohemian Rhapsody',
        artist: 'Queen',
        album: 'A Night at the Opera',
        year: 1975,
        genre: 'Rock',
        duration: '5:55',
        plays: 1000000,
    },
    {
        id: '2',
        title: 'Stairway to Heaven',
        artist: 'Led Zeppelin',
        album: 'Led Zeppelin IV',
        year: 1971,
        genre: 'Rock',
        duration: '8:02',
        plays: 800000,
    },
    {
        id: '3',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        genre: 'Pop',
        duration: '4:54',
        plays: 1200000,
    },
    {
        id: '4',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        genre: 'Pop',
        duration: '4:54',
        plays: 1200000,
    },
    {
        id: '5',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        genre: 'Pop',
        duration: '4:54',
        plays: 1200000,
    },
    {
        id: '6',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        genre: 'Pop',
        duration: '4:54',
        plays: 1200000,
    },
    {
        id: '7',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        genre: 'Pop',
        duration: '4:54',
        plays: 1200000,
    },
    {
        id: '8',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        genre: 'Pop',
        duration: '4:54',
        plays: 1200000,
    },
    {
        id: '9',
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: 1982,
        genre: 'Pop',
        duration: '4:54',
        plays: 1200000,
    },
];